export default {
    splashLogo: require('../assets/images/splash.png'),
    logoImage: require('../assets/images/logo.jpeg'),
    eyeIcon: require('../assets/images/eye-line.png'),
    forgetPassword: require('../assets/images/icForgotGraphic.png'),
    drawerWhiteIcon: require('../assets/images/drawerWhite.png'),
    inactiveHomeTab: require('../assets/images/ic_home.png'),
    inactiveProfile: require('../assets/images/ic_profile.png'),
    inactiveLibrary: require('../assets/images/study.png'),
    inactivePremium: require('../assets/images/ic_book.png'),
    appBackgroundIcon: require('../assets/images/marbleBackground.jpg'),
    profilePlaceHolderIcon: require('../assets/images/IdentityProfile.png'),
    writePostIcon: require('../assets/images/ic_write-post.png'),
    list1: require('../assets/images/list1.jpeg'),
    list2: require('../assets/images/list2.jpeg'),
    list3: require('../assets/images/list3.jpeg'),
    list4: require('../assets/images/list4.jpeg'),
    exit_icon: require('../assets/images/exit.png'),
}