export default {
    SPLASH_SCREEN: 'splashScreen',
    ONBOARDING_SCREENS: 'OnboardingScreen',
    LOGIN: 'Login',
    SIGN_UP: 'signUp',
    FORGET_PASSWORD: 'forgetPassword',
    SETTING_SCREENS_STACK: 'settingScreenStack',
    HOME_STACK: 'homeStack',
    PROFILE: 'profile',
    HOME_SCREEN: 'homeScreen',
    MEMBER_LIST_SCREEN: 'membersList',
    MEMBERS_STACK: 'membersStack',
    MAIN_BOTTOM_TAB_STACK: 'mainBottomTabStack',
    HOME_DRAWER: 'homeDrawer',
    SETTINGS_SCREEN: 'settingScreen',
    WINS_SCREEN: 'WinsScreen',
    WINS_STACK: 'WinsStack',
    SCHEDULE_SCREEN: 'ScheduleScreen',
    SCHEDULE_STACK: 'ScheduleStack',
    WRITE_POST: 'writePost',
}